# This file is part of dirtsand.
#
# dirtsand is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# dirtsand is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with dirtsand.  If not, see <http://www.gnu.org/licenses/>.

version: "3.8"

services:
  db:
    build:
      context: ./db
    env_file: .env
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/

  moul:
    build:
        context: .
    depends_on: [db]
    env_file: .env
    ports:
      - "14617:14617/tcp"
      - "8080:8080/tcp"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ${HOST_CONFIG_DIRECTORY}
        target: /opt/dirtsand/etc/

      - type: bind
        source: ${HOST_AUTHSRV_DIRECTORY}
        target: /opt/dirtsand/lib/authsrv/

      - type: bind
        source: ${HOST_FILESRV_DIRECTORY}
        target: /opt/dirtsand/lib/filesrv/

      - type: bind
        source: ${HOST_AGE_DIRECTORY}
        target: /opt/dirtsand/lib/dat/

      - type: bind
        source: ${HOST_SDL_DIRECTORY}
        target: /opt/dirtsand/lib/SDL/

volumes:
  db:
