# This file is part of dirtsand.
#
# dirtsand is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# dirtsand is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with dirtsand.  If not, see <http://www.gnu.org/licenses/>.

version: "3.8"

services:
  db:
    environment:
      - POSTGRES_USER=dirtsand
      - POSTGRES_PASSWORD=MySuperSecretPassword
      - POSTGRES_DB=dirtsand

  moul:
    environment:
      - DS_HOST=127.0.0.1
      - DS_DROIDKEY=31415926535897932384626433832795
      - POSTGRES_USER=dirtsand
      - POSTGRES_PASSWORD=MySuperSecretPassword
      - POSTGRES_DB=dirtsand

    ports:
      - "14617:14617/tcp"
      - "8080:8080/tcp"

    volumes:
      - type: bind
        source: ./build/etc
        target: /opt/dirtsand/etc/

      - type: bind
        source: ./build/authserv
        target: /opt/dirtsand/lib/authsrv/

      - type: bind
        source: ./build/fileserv
        target: /opt/dirtsand/lib/filesrv/

      - type: bind
        source: ./build/dat
        target: /opt/dirtsand/lib/dat/

      - type: bind
        source: ./build/SDL
        target: /opt/dirtsand/lib/SDL/
