# This file is part of dirtsand.
#
# dirtsand is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# dirtsand is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with dirtsand.  If not, see <http://www.gnu.org/licenses/>.

version: "3.8"

# This is the baseline dirtsand service definition -- the bare minimum to start a dirtsand service.
# However, this is insufficient to actually start a shard. You will need to use docker-compose.local.yml
# to setup a trivial local shard (see also: `docker-compose -f`) or copy and customize it to deploy
# a real shard (see also: `docker stack`) This is due to multi-value keys merging instead of overriding.
# See also: https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/

  moul:
    build:
        context: .
    depends_on: [db]
    stdin_open: true
    tty: true

volumes:
  db:
